# Generated by Django 2.2.3 on 2020-04-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptid', models.IntegerField()),
                ('deptname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depid', models.IntegerField()),
                ('depname', models.CharField(max_length=30)),
                ('depdob', models.DateField()),
                ('depgender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.IntegerField()),
                ('docname', models.CharField(max_length=30)),
                ('fee', models.IntegerField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=30)),
                ('etype', models.CharField(choices=[('RET', 'retired'), ('EXEC', 'executive'), ('NEXEC', 'non-executive')], default='EXEC', max_length=5)),
                ('edob', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('fine', models.BooleanField(default=0)),
                ('finedate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUN', 'sunday'), ('MON', 'monday'), ('TUES', 'tuesday'), ('WED', 'wednesday'), ('THURS', 'thursday'), ('FRI', 'friday'), ('SAT', 'saturday')], max_length=5)),
                ('shift1', models.BooleanField()),
                ('shift2', models.BooleanField()),
                ('shift3', models.BooleanField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patid', models.IntegerField()),
                ('is_employee', models.BooleanField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Dependent')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='dependent',
            name='empl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Employee'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateField()),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient')),
                ('sched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Schedule')),
            ],
        ),
    ]
