# Generated by Django 2.2.3 on 2020-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20200429_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empmail',
            field=models.EmailField(default='no_email@gmail.com', max_length=254),
        ),
    ]
