# Generated by Django 2.2.3 on 2020-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_employee_empmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='finedate',
            field=models.DateField(default=None),
        ),
    ]
